-- CONTROLE FINANCEIRO V1
-- Execute no SQL Editor do Supabase.
-- Depois crie os usuários no Auth > Users e seus perfis em public.perfis.

create extension if not exists pgcrypto;

create type public.app_role as enum ('FATURAMENTO','FINANCEIRO');

create table public.empresas (
  id bigint generated by default as identity primary key,
  nome text not null unique,
  cnpj text,
  ativo boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.perfis (
  id uuid primary key references auth.users(id) on delete cascade,
  nome text not null,
  username text not null unique,
  role public.app_role not null,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.transacoes (
  id bigint generated by default as identity primary key,
  empresa_id bigint not null references public.empresas(id),
  data date not null,
  movimentacao text not null,
  descricao text,
  valor numeric(15,2) not null,
  meio_pagamento text,
  ultimos_digitos_cartao varchar(4),
  titular_cartao text,
  categoria text,
  qtd_recibos_notas integer not null default 0,
  valor_nota_fiscal numeric(15,2),
  valor_pago_cartao numeric(15,2),
  comprovante_conta_simples boolean not null default false,
  lancado_sankhya boolean not null default false,
  sankhya_ok boolean not null default false,
  conferencia_obs varchar(20),
  fingerprint text not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint transacoes_card_digits_chk check (ultimos_digitos_cartao is null or ultimos_digitos_cartao ~ '^[0-9]{4}$'),
  constraint transacoes_obs_len_chk check (conferencia_obs is null or char_length(conferencia_obs) <= 20)
);

create index idx_transacoes_empresa_data on public.transacoes(empresa_id,data);
create index idx_transacoes_data on public.transacoes(data);
create index idx_transacoes_card on public.transacoes(ultimos_digitos_cartao);

create table public.auditoria (
  id bigint generated by default as identity primary key,
  usuario_id uuid references auth.users(id),
  transacao_id bigint references public.transacoes(id) on delete set null,
  acao text not null,
  dados_anteriores jsonb,
  dados_novos jsonb,
  created_at timestamptz not null default now()
);

create index idx_auditoria_transacao on public.auditoria(transacao_id);
create index idx_auditoria_usuario on public.auditoria(usuario_id);
create index idx_auditoria_created on public.auditoria(created_at desc);

insert into public.empresas(nome) values
  ('Instituto João Bittar'),
  ('Bittar Neurociencia')
on conflict (nome) do nothing;

-- Trigger updated_at
create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger trg_perfis_updated_at
before update on public.perfis
for each row execute function public.set_updated_at();

create trigger trg_transacoes_updated_at
before update on public.transacoes
for each row execute function public.set_updated_at();
